language: android
jdk: oraclejdk8

android:
  components:
    - tools #latest for "builtin" sdk
    - tools #latest
    - platform-tools #latest
    - build-tools-26.0.1
    - android-25
    - extra-android-m2repository

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-unlimited-jce-policy

before_install:
- export ANDROID_HOME=/usr/local/android-sdk
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo "sdk.dir=$ANDROID_HOME" > local.properties

script:
  - ./gradlew clean
  - ./gradlew testReleaseUnitTestCoverage
